name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update ubuntu
      run: sudo apt-get update

    - name: Add Inkspace repo
      run: sudo add-apt-repository ppa:inkscape.dev/stable

    - name: Prepare for install
      run: sudo apt-get update

    - name: Install dependancies
      run: sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra biber inkscape

    - name: Compile latex
      run: make
